CREATE TABLE IF NOT EXISTS PHONEBOOK (
    user_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS TEST (
    c1 varchar(10),
    c2 varchar(10),
    c3 varchar(10)
);

CREATE TABLE IF NOT EXISTS PUBLIC.POST_EXAMPLE
(
    POST_ID        BIGINT AUTO_INCREMENT,
    BOARD_ID       INT,
    BOARD_NAME     CHARACTER VARYING(100),
    CREATE_AT      TIMESTAMP NOT NULL,
    UPDATE_AT      TIMESTAMP NOT NULL,

    USER_ID        BIGINT NOT NULL,
    USER_EMAIL     CHARACTER VARYING(255),
    USER_NAME      CHARACTER VARYING(255),

    TITLE          VARCHAR(200),
    CONTENT        TEXT,

    primary key (POST_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.POST_FILES
(
    POST_ID        BIGINT NOT NULL,
    BOARD_ID       INT,

    FILE_NAME      CHARACTER VARYING(255),
    FILE_ORDER     INT,
    FILE_PATH      CHARACTER VARYING(255),

    constraint FK_POSTFILES_POST
        foreign key (POST_ID) references PUBLIC.POST_EXAMPLE (POST_ID)
);